<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ARS-NBT-LAP-250" ignored="0" name="Opus7" tests="10" failures="1" timestamp="27 May 2022 09:06:32 GMT" time="265.811" errors="0">
  <testcase name="verifyVendorAccountLogin" time="9.452" classname="com.opus.testcases.TC_RaiseInsufficiency_05"/>
  <testcase name="VerifyAssigningCheckToFieldExecutive" time="29.022" classname="com.opus.testcases.TC_RaiseInsufficiency_05"/>
  <testcase name="verifyUpdateCheckDetails" time="110.041" classname="com.opus.testcases.TC_RaiseInsufficiency_05"/>
  <testcase name="verifyAdminApproverTl" time="17.3" classname="com.opus.testcases.TC_RaiseInsufficiency_05"/>
  <testcase name="verifyAdminApprover" time="36.58" classname="com.opus.testcases.TC_RaiseInsufficiency_05"/>
  <testcase name="verifyCheckStatusSummaryInsufficient" time="22.252" classname="com.opus.testcases.TC_RaiseInsufficiency_05"/>
  <testcase name="verifyBridgeFullfillCheckInsufficiency" time="25.331" classname="com.opus.testcases.TC_RaiseInsufficiency_05"/>
  <testcase name="verifyDocumentsReceivedAddressProof" time="11.289" classname="com.opus.testcases.TC_RaiseInsufficiency_05"/>
  <testcase name="verifyInsuffFullfillBucketCount" time="1.219" classname="com.opus.testcases.TC_RaiseInsufficiency_05">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.opus.testcases.TC_RaiseInsufficiency_05.verifyInsuffFullfillBucketCount(TC_RaiseInsufficiency_05.java:240)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verifyInsuffFullfillBucketCount -->
  <testcase name="verifyInsuffFullfillApprovalMapping" time="0.0" classname="com.opus.testcases.TC_RaiseInsufficiency_05">
    <skipped/>
  </testcase> <!-- verifyInsuffFullfillApprovalMapping -->
</testsuite> <!-- Opus7 -->
